"""
Fake EV Detector & Model Delusion Protection Engine.
Detects phantom edges caused by model bias, small sample sizes, or missing market information.
Applies Bayesian shrinkage towards sharp market consensus (Pinnacle de-vigged) to extract True EV.

Status taxonomy (precise):
  FAKE_EV              — Raw EV > 0 but True EV ≤ 0 after calibration. Rejected.
  MARGINAL_EV          — True EV > 0 but below min_edge. No bet.
  HIGH_DIVERGENCE_WARNING — Model vs market gap is large. Reduced trust.
  REJECTED_LONGSHOT    — Longshot + high divergence. Structural rejection.
  MODEL_TRUE_EV        — Passed all calibration/shrinkage/anti-delusion tests.
                         NOTE: This is a model-calibrated positive-EV candidate.
                         It does NOT mean the edge is empirically proven.
                         Empirical proof requires: CLV > 0 over N≥200 bets +
                         out-of-sample calibration (ECE < 3%) + market confirmation.
  NO_EDGE              — Raw EV ≤ min_edge from the start.
"""

from typing import Any

from unified_betting_core.config import MIN_EDGE


class FakeEVDetector:
    """
    Detects and filters out "Fake EV" (false edges generated by model delusion).

    Why Fake EV happens:
    - Pure statistical models (Poisson/XGBoost on goals) do not observe live breaking news,
      lineup rotations, motivational asymmetric incentives, or sudden tactical shifts.
    - Extreme underdog probabilities are often distorted by the model's distributional assumptions.
    - Example: Poisson predicting 25% for Sunderland vs Man City at odds 10.0 (+150% fake EV).

    Mitigation Strategy:
    1. Divergence Test: Flags when |P_model - P_devig| > max_divergence.
    2. Longshot Penalty: Extra scrutiny on odds > 5.50 or P_devig < 0.15.
    3. Bayesian Shrinkage: Blends model probability towards sharp market consensus:
       P_calibrated = w * P_model + (1 - w) * P_devig
    4. True EV Verification: Computes EV using P_calibrated.
       If Raw_EV > 0 but True_EV <= 0 -> Classify as FAKE_EV and REJECT.
    """

    def __init__(
        self,
        min_edge: float = MIN_EDGE,
        max_divergence: float = 0.14,  # 14% absolute probability gap
        max_rel_divergence: float = 0.85,  # 85% relative gap vs market
        base_model_weight: float = 0.28,  # Model carries 28% weight, sharp market carries 72%
        longshot_odds_threshold: float = 5.50,
    ):
        self.min_edge = min_edge
        self.max_divergence = max_divergence
        self.max_rel_divergence = max_rel_divergence
        self.base_model_weight = base_model_weight
        self.longshot_odds_threshold = longshot_odds_threshold

    def calculate_shrinkage_weight(
        self, p_model: float, p_devig: float, odds: float
    ) -> float:
        """
        Dynamically adjusts model weight based on market confidence and divergence.
        """
        abs_div = abs(p_model - p_devig)
        weight = self.base_model_weight

        # If odds are high (longshot territory), lean even more heavily into sharp market
        if odds >= self.longshot_odds_threshold or p_devig < 0.12:
            weight = max(weight * 0.5, 0.10)

        # If divergence is severe, shrink weight further to protect capital
        if abs_div > self.max_divergence:
            weight = max(weight * 0.4, 0.08)
        elif abs_div < 0.03:
            # High alignment between model and market -> allow higher model trust
            weight = min(weight * 1.35, 0.45)

        return round(weight, 4)

    def calibrate_probability(
        self, p_model: float, p_devig: float, odds: float
    ) -> tuple[float, float]:
        """
        Calculates the Bayesian shrinkage calibrated probability:
        P_calibrated = w * P_model + (1 - w) * P_devig
        Returns (p_calibrated, weight_used)
        """
        if p_devig <= 0:
            return p_model, 1.0

        weight = self.calculate_shrinkage_weight(p_model, p_devig, odds)
        p_calibrated = (weight * p_model) + ((1.0 - weight) * p_devig)
        return round(p_calibrated, 5), weight

    def audit_bet(
        self, outcome: str, p_model: float, p_devig: float, best_odds: float
    ) -> dict[str, Any]:
        """
        Conducts a deep sharp audit of a candidate bet.
        Evaluates Raw EV vs True EV and detects Fake EV / Delusion.
        """
        if best_odds <= 1.0 or p_model <= 0:
            return {
                "outcome": outcome,
                "status": "INVALID",
                "is_valid_bet": False,
                "reason": "Invalid odds or non-positive probability",
            }

        # 1. Raw EV calculation
        raw_ev = (p_model * best_odds) - 1.0
        raw_ev_pct = round(raw_ev * 100, 2)

        # 2. Market Implied & De-vig
        market_fair_odds = round(1.0 / p_devig, 3) if p_devig > 0 else 999.0
        model_fair_odds = round(1.0 / p_model, 3) if p_model > 0 else 999.0

        # 3. Divergence metrics
        abs_divergence = abs(p_model - p_devig)
        rel_divergence = abs_divergence / max(p_devig, 0.001)

        # 4. Bayesian Calibration (Shrinkage towards sharp consensus)
        p_calibrated, weight = self.calibrate_probability(p_model, p_devig, best_odds)
        calibrated_fair_odds = round(1.0 / p_calibrated, 3)

        # 5. True EV calculation using calibrated probability
        true_ev = (p_calibrated * best_odds) - 1.0
        true_ev_pct = round(true_ev * 100, 2)

        # 6. Classification Logic
        is_longshot = best_odds >= self.longshot_odds_threshold
        high_divergence = (
            abs_divergence > self.max_divergence
            or rel_divergence > self.max_rel_divergence
        )

        status = "NO_EDGE"
        is_valid_bet = False
        reasons = []

        if raw_ev > self.min_edge:
            if true_ev <= 0:
                status = "FAKE_EV"
                is_valid_bet = False
                reasons.append(
                    f"Model delusion detected: Raw EV is +{raw_ev_pct}%, but true EV after market shrinkage is {true_ev_pct}%."
                )
            elif true_ev < self.min_edge:
                status = "MARGINAL_EV"
                is_valid_bet = False
                reasons.append(
                    f"Shrunk EV (+{true_ev_pct}%) falls below threshold ({self.min_edge * 100:.1f}%)."
                )
            elif is_longshot and high_divergence:
                status = "REJECTED_LONGSHOT"
                is_valid_bet = False
                reasons.append(
                    f"Extreme underdog odds ({best_odds:.2f}) with high divergence ({abs_divergence * 100:.1f}%) rejected by risk guard."
                )
            elif high_divergence:
                status = "HIGH_DIVERGENCE_WARNING"
                # If true_ev is still robust even with strong shrinkage, allow with reduced stake
                is_valid_bet = true_ev >= (self.min_edge * 1.5)
                reasons.append(
                    f"Large divergence from sharp market consensus (|Δ|={abs_divergence * 100:.1f}%)."
                )
            else:
                status = "MODEL_TRUE_EV"
                is_valid_bet = True
                reasons.append(
                    "Passed all calibration/shrinkage/anti-delusion tests. "
                    "MODEL-CALIBRATED positive-EV candidate. "
                    "Empirical proof (CLV track record) still pending."
                )
        else:
            status = "NO_EDGE"
            is_valid_bet = False
            reasons.append(
                f"Raw EV ({raw_ev_pct}%) is below minimum edge ({self.min_edge * 100:.1f}%)."
            )

        return {
            "outcome": outcome,
            "best_odds": round(best_odds, 3),
            "p_model": round(p_model, 4),
            "model_fair_odds": model_fair_odds,
            "p_devig": round(p_devig, 4),
            "market_fair_odds": market_fair_odds,
            "p_calibrated": round(p_calibrated, 4),
            "calibrated_fair_odds": calibrated_fair_odds,
            "abs_divergence": round(abs_divergence, 4),
            "abs_divergence_pct": round(abs_divergence * 100, 2),
            "raw_ev": round(raw_ev, 4),
            "raw_ev_pct": raw_ev_pct,
            "true_ev": round(true_ev, 4),
            "true_ev_pct": true_ev_pct,
            "shrinkage_weight": weight,
            "status": status,
            "is_valid_bet": is_valid_bet,
            "reasons": reasons,
        }
